# TODO: random wallpapers for each unique monitor
wallpaper {
    monitor = HDMI-A-1
    path = ~/.wallpapers
    # recursive = true
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = ~/.wallpapers
    # recursive = true
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = ~/.wallpapers
    # recursive = true
    fit_mode = cover
}
